ProtonMail/go-proton-api

.gitignore, manager_auth.go, manager_auth_types.go
In POST `/auth/v4/2fa` you should be including the FIDO2 object only if it's filled, if not we'll attempt validating it
Docs specify
> TwoFactorCode either this or the FIDO2 object
=> fix(GODT-2242): Don't send any 2fa information if not needed.

server/backend/api.go, server/backend/backend.go, server/backend/message.go, server/messages.go
When importing message without from or sender the API will add empty address.
=> test(GODT-2181): match API behaviour for import

response.go
Error code 6003 is marked as deprecated but still returned by login for non valid emails.
=> fix(GODT-2246): added missing API error code.

client.go, contact_types.go, manager.go, manager_builder.go, message_import.go, message_import_types.go, message_types.go, response.go, server/messages.go, server/router.go
NetError is an error type returned when no response was received from the API. This allows callers to determine whether their call failed due to a network level error.
Additionally, proton.APIError now has Status to see what the status code was in the response that triggered the error.
=> feat: Implement NetError (and rename proton.Error to proton.APIError)

server/backend/api.go, server/backend/message.go, server/messages.go
When creating the draft we need to convert the parentID into valid reference to be stored as references/in-reply-to.
Then on message creation on the fake server we need to populate the in-reply-to/references fields.
=> feat(GODT-1556): simulate reply behaviour on fakeAPI side.

server/backend/types.go
The event ID needs to appear in the URL request. As such, it can't contain any forward slashes.
=> fix: Use URL encoding for event IDs

server/backend/message.go, server/server_test.go
The 'Scheduled' label in fake server is now managed using the `proton.MessageFlagScheduledSend` flag.
=> feat(GODT-1264): Scheduled label managed by flag in fake server.

manager_test.go, response.go
In the rare cases where the `APIError` deserialization routine fails, ensure that all >=400 error codes are still reported as API errors so that client libraries can correctly handle this.
=> fix(GODT-2512): Catch unhandled API errors

message.go, message_types.go
Do not call label/unlabel operations in parallel when we have more than 150 messages. This can cause the operation to fail in the backend.
This patch also improves the error message by returning the first error message for the failed operation.
=> fix(GODT-2574): Use sequential operations for label/unlabel

response.go, response_test.go
Details can be any kind of JSON type, not just JSON objects.
=> fix(GODT-2726): Correct Parsing of Details error

server/backend/backend.go, server/helper_test.go, server/server_builder.go, server/server_test.go
Implement basic message deduplication for GPA server. This functionality is opt-in. It's not enabled by default in order to not break any existing tests are written against the previous behavior.
=> test(GODT-2578): Message Dedup for Server

message.go, server/server_test.go
Add `GetAllMessageIDs` which is the old behavior and add a new function `GetMessageIDs` which only retrieves the given messages up to that limit.
=> fix(2822): Refactor GetMessageIDs

go.mod, go.sum, header_types.go, header_types_test.go, message_build.go, server/backend/message.go
Ensure order of parsed header field is recorded alongside the values.
=> fix(GODT-2212): Preserve header order when building messages

server/backend/api.go, server/backend/attachment.go
Inline attachment order is preserved using the attachment contentID.
Message attachment IDs list  should then be computed with contentID properly sorted to ensure inline attachments are rendered in the right order when we get the message from the server.
=> fix(GODT-3036): Keep contentID order for attachment in FakeServer.

message_send_types.go, message_send_types_test.go
Add a new send package type for clear-signed messages.
Trailing whitespace is stripped for this package type. The stripping of trailing whitespace has been removed for other package types.
=> feat(GODT-1224): Add support for clear-signed sending packages

contact_types.go, helper_test.go, manager_report_types.go, message_import.go, message_import_types.go, server/contacts.go, server/messages.go, server/server_test.go
The original fixes to parse the HV error message unfortunately caused those corrected error routes to start failing when tested against live proton servers.
Since HV error parsing was improved in a subsequent patch, we no longer needs the original fix and can therefore revert the changes that are causing issues.
=> fix(GODT-3106): Fix broken import route

contact.go, contact_card.go, server/backend/account.go, server/backend/api.go, server/backend/contact.go, server/contacts.go, server/server_test.go
Rather than only fetching the total in on request and discarding all the data, re-use the first page of data and then collect more of them if the data set exceeds the page size.
This patch also includes various fixes to the GPA server to mimic proton server behavior.
=> fix(GODT-3117): Improve Contact Info Retrieval

server/backend/api.go, server/backend/updates.go, server/server.go
When changing the address order, trigger address updated events and if the primary address changes, trigger a user info event.
=> feat(GODT-3129): Trigger events when address order changes

server/backend/api.go, server/backend/api_auth.go, server/backend/attachment.go, server/backend/backend.go, server/backend/report.go
Access to all the fake server state is now guarded by a single RWLock rather then multiple locks per category. It has been observed in the past that this could lead to deadlocks in Bridge unit tests at random.
=> fix(GODT-3124): Simplify locking in GPA server

response.go
=> feat(BRIDGE-14): Missing response code

message_import.go
gomock does not support generics. In order to be able to mock `ImportMessage()`, we introduce a type definition.
=> feat(IMEX-9): introduce a typedef to be able to mock ImportMessages.

client_features.go, manager_features.go, server/backend/api.go, server/backend/backend.go, server/features.go, server/router.go, server/server.go
Support feature flags in GPA, calling and parsing responses.
=> Feat/BRIDGE-119 - Feature flag support

message_encrypt.go
Although explicitly documented in the package source code (by a former Bridge dev, might I add), we did not perform this check.  Ref: https://github.com/golang/text/blob/master/encoding/ianaindex/ianaindex.go#L75
In rare cases, this would cause a nil pointer deref and subsequent crash on Bridge.
=> fix(BRIDGE-355): check for nil encoder to prevent panic
